name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install --prefix ./Software_Code/frontend
    - run: npm run build --prefix ./Software_Code/frontend --if-present
    - run: npm test --prefix ./Software_Code/frontend
      env:
        CI: true
